export interface SampleField {
  title: string; desc: string; steps: string;
  exp: string; act: string; env: string;
  sev: string; pri: string; comp: string;
  rep: string; exc: string; att: string;
}

export const SAMPLES: SampleField[] = [
  {
    title: 'Search page crashes on special characters in query string',
    desc: 'When users type special characters like &, %, #, or ? into the global search bar, the results page throws a 500 error. Affects all users on web and occurs ~8 out of 10 times.',
    steps: '1. Log in at staging.example.com\n2. Click the global search bar\n3. Type a query with special chars e.g. "Q&A session"\n4. Press Enter\n5. Observe the crash',
    exp: 'Search results load, or an empty state if no matches found.',
    act: 'Blank white screen with 500 Internal Server Error in console. Page needs hard refresh.',
    env: 'Windows 11, Chrome 120, App v3.1.2 (build 4821), Staging',
    sev: 'High', pri: 'P2', comp: 'Search / Query Engine', rep: 'Quinn Arora / QA Team',
    exc: "TypeError: Cannot read properties of undefined (reading 'encode')\n  at SearchController.query (search.js:87:14)\n  at async Router.handle (/routes/search.js:23:5)\nHTTP 500 Internal Server Error",
    att: 'Screenshot: drive.example.com/shot.png\nHAR: drive.example.com/trace.har',
  },
  {
    title: 'Login button unresponsive on Safari 17 with 2FA enabled',
    desc: 'After entering valid credentials and the 6-digit OTP on Safari 17, clicking the Sign In button does nothing. No loading state, no error. Works fine on Chrome and Firefox. Affects ~20% of user base.',
    steps: '1. Open Safari 17 on macOS Sonoma\n2. Navigate to app.example.com/login\n3. Enter valid email and password\n4. Enter valid 6-digit OTP from authenticator app\n5. Click "Sign In"\n6. Observe — nothing happens',
    exp: 'User is authenticated and redirected to dashboard.',
    act: 'Button appears to click (ripple animation), then reverts. No API call is made. No error message displayed.',
    env: 'macOS Sonoma 14.1, Safari 17.1, App v4.2.0, Production',
    sev: 'Critical', pri: 'P1', comp: 'Auth / 2FA', rep: 'Ana Silva / Customer Support',
    exc: 'Unhandled Promise Rejection: TypeError: window.crypto.subtle.digest is not a function\n  at computeHOTP (otp.js:34)\n  at handleSubmit (LoginForm.jsx:89)',
    att: 'Video recording: drive.example.com/safari-login-bug.mp4',
  },
  {
    title: 'Checkout total displays $0.00 when promo code is applied',
    desc: 'Applying a valid promo code "SAVE20" to a cart with items resets the displayed total to $0.00 instead of showing the discounted price. The charge still goes through correctly on the payment provider side, but users see $0 and abandon cart at high rate.',
    steps: '1. Add 2+ items to cart\n2. Proceed to checkout\n3. Enter promo code "SAVE20" in the coupon field\n4. Click Apply\n5. Observe the order total',
    exp: 'Order total updates to show 20% discount applied, e.g. $80.00 from $100.00.',
    act: 'Order total shows $0.00. "Place Order" button is greyed out.',
    env: 'All browsers, App v5.0.1, Production and Staging',
    sev: 'Critical', pri: 'P1', comp: 'Checkout / Pricing Engine', rep: 'Dev Team',
    exc: 'ReferenceError: discountedTotal is not defined\n  at CartSummary.render (CartSummary.js:112)',
    att: 'Screenshot of $0.00 total: drive.example.com/checkout-zero.png',
  },
  {
    title: 'Profile photo upload silently fails for PNG files over 2MB',
    desc: 'When users attempt to upload a PNG profile photo larger than 2MB, the upload spinner appears briefly and then disappears with no error message. The old photo remains. JPEG files of the same size upload successfully.',
    steps: '1. Log in\n2. Navigate to Settings > Profile\n3. Click "Change Photo"\n4. Select a PNG file > 2MB\n5. Click Upload\n6. Observe',
    exp: 'Photo uploads and thumbnail updates, or a clear error message about file size limit.',
    act: 'Spinner shows for ~2s then disappears. No error. Old photo unchanged. Network tab shows 413 response with no UI feedback.',
    env: 'Chrome 119, Windows 10, App v3.8.5, Production',
    sev: 'Medium', pri: 'P3', comp: 'File Upload / Profile', rep: 'QA Team',
    exc: 'HTTP 413 Request Entity Too Large\nPOST /api/v1/users/avatar 413',
    att: 'Network HAR: drive.example.com/upload-413.har',
  },
  {
    title: 'Dashboard date filter resets to "All Time" on page refresh',
    desc: 'Users select a custom date range on the analytics dashboard and the charts update correctly. However, pressing F5 or refreshing the browser resets the date filter back to "All Time" instead of preserving the selection. This forces users to re-select every session.',
    steps: '1. Log in as any user with dashboard access\n2. Navigate to Analytics > Dashboard\n3. Set date range to "Last 30 Days"\n4. Verify charts update\n5. Press F5 or refresh browser\n6. Observe the date filter value',
    exp: 'Date range persists on refresh (should be stored in URL params or localStorage).',
    act: 'Date filter resets to "All Time". Charts show all-time data.',
    env: 'All browsers, App v4.1.0, Production',
    sev: 'Medium', pri: 'P3', comp: 'Analytics / Dashboard', rep: 'Product Team',
    exc: '',
    att: '',
  },
  {
    title: 'Bulk email send freezes UI when recipient list exceeds 500',
    desc: 'The marketing email composer freezes the browser tab when a campaign is sent to more than 500 recipients. The tab becomes unresponsive for 30–60 seconds. For lists over 2000 recipients, the tab crashes entirely.',
    steps: '1. Log in as marketing user\n2. Create a new campaign\n3. Import a CSV with 500+ email addresses\n4. Compose email content\n5. Click "Send Campaign"\n6. Observe browser behavior',
    exp: 'Campaign queues asynchronously and user sees a progress indicator.',
    act: 'Browser tab freezes for 30-60s. For 2000+ recipients, tab crashes with "Aw Snap" error.',
    env: 'Chrome 120, 8GB RAM MacBook, App v2.9.3, Production',
    sev: 'High', pri: 'P2', comp: 'Email / Campaign Engine', rep: 'Marketing Team',
    exc: 'JavaScript heap out of memory\n  at Array.map (email-composer.js:287)\nOutOfMemoryError: Allocation failed - JavaScript heap out of memory',
    att: 'Performance profile: drive.example.com/email-perf.json',
  },
  {
    title: 'PDF export generates blank pages for reports with charts',
    desc: 'Exporting any report that contains chart/graph elements to PDF results in a document where chart pages are blank white. Text sections export correctly. The issue is consistent across all report types with visualizations.',
    steps: '1. Navigate to Reports\n2. Open any report containing a chart (e.g. Monthly Revenue)\n3. Click Export > PDF\n4. Download and open the PDF\n5. Navigate to chart pages',
    exp: 'PDF renders charts as vector graphics or high-resolution images.',
    act: 'Chart pages are blank white in the PDF. Text pages render correctly.',
    env: 'macOS 13, Chrome 119, App v3.5.0, Production',
    sev: 'High', pri: 'P2', comp: 'PDF Export / Reporting', rep: 'QA Team',
    exc: 'Error: Failed to capture canvas element\n  at PDFExporter.renderChart (pdf-export.js:156)\nTypeError: Cannot read properties of null (reading \'toDataURL\')',
    att: 'Sample broken PDF: drive.example.com/broken-export.pdf',
  },
  {
    title: 'API rate limit returns 200 OK instead of 429 Too Many Requests',
    desc: 'The REST API rate limiter is incorrectly returning HTTP 200 with an empty body when the limit is exceeded instead of HTTP 429. Third-party integrators are not detecting rate limit breaches and continue hammering the API, causing performance degradation for all users.',
    steps: '1. Obtain valid API key\n2. Send more than 100 requests within 60 seconds to any endpoint\n3. Observe HTTP response code on the 101st request\n4. Check response body',
    exp: 'HTTP 429 Too Many Requests with Retry-After header and error JSON body.',
    act: 'HTTP 200 OK with empty response body {}.',
    env: 'All clients, API v2, Production',
    sev: 'High', pri: 'P2', comp: 'API Gateway / Rate Limiting', rep: 'Backend Team',
    exc: 'HTTP 200 OK (expected 429)\nX-RateLimit-Remaining: 0\nContent-Length: 2',
    att: 'Postman collection: drive.example.com/rate-limit-test.json',
  },
  {
    title: 'Notification emails contain broken image links in dark mode',
    desc: 'Notification emails sent for order confirmations and password resets display broken image placeholders when viewed in dark mode in Gmail and Outlook. The images use absolute HTTP URLs that redirect to HTTPS, which email clients block.',
    steps: '1. Trigger any notification email (e.g. place an order)\n2. Open the email in Gmail with dark mode enabled\n3. Observe the email header and logo images',
    exp: 'Logo and product images render correctly in dark mode.',
    act: 'Images show as broken placeholders (red X) in Gmail dark mode. Images load correctly in light mode.',
    env: 'Gmail (web, dark mode), Outlook 365, App v4.0.0, Production',
    sev: 'Medium', pri: 'P3', comp: 'Email Templates / Notifications', rep: 'Design Team',
    exc: 'Mixed Content Warning: http:// image loaded in https:// context (blocked)',
    att: 'Screenshot: drive.example.com/email-dark-broken.png',
  },
  {
    title: 'Drag-and-drop kanban cards lose assignment on drop in Firefox',
    desc: 'On the project management board, dragging a task card from one column to another works visually in Firefox but the assignee field is silently cleared in the database. The card appears in the new column but shows "Unassigned". Works correctly in Chrome.',
    steps: '1. Open Firefox 120\n2. Navigate to Project Board\n3. Find a card with an assignee\n4. Drag it to a different column\n5. Release and observe\n6. Refresh page and check assignee',
    exp: 'Card moves to new column; assignee preserved.',
    act: 'Card moves visually but assignee is cleared. After refresh, card shows "Unassigned".',
    env: 'Firefox 120, Windows 11, App v3.2.1, Production',
    sev: 'High', pri: 'P2', comp: 'Kanban Board / Drag-Drop', rep: 'QA Team',
    exc: "PATCH /api/tasks/4821 → payload missing 'assignee_id' field in Firefox DragEvent",
    att: 'Network log showing missing field: drive.example.com/ff-drag-log.txt',
  },
  {
    title: 'Mobile app crashes on launch when offline on iOS 17',
    desc: 'The iOS app crashes immediately on launch when the device has no internet connection. The app should display a cached version of the last-viewed screen and show an offline banner. Only affecting iOS 17, iOS 16 shows the cached screen correctly.',
    steps: '1. Install app v2.3.0 on iPhone with iOS 17\n2. Open app once to populate cache\n3. Enable Airplane Mode\n4. Force close and reopen app\n5. Observe crash',
    exp: 'App launches showing cached content and "You are offline" banner.',
    act: 'App crashes to home screen immediately. Crash log shows null pointer dereference.',
    env: 'iPhone 15, iOS 17.1, App v2.3.0',
    sev: 'Critical', pri: 'P1', comp: 'iOS App / Offline Mode', rep: 'Mobile QA',
    exc: "Fatal Exception: NSInvalidArgumentException\n  'NSNull' valueForKey: 'url'\n  0  CoreFoundation  0x1a3b2 __exceptionPreprocess\n  1  AppDelegate     0x10234 -[CacheManager loadCached:]\nNullPointerException at CacheManager.m:89",
    att: 'Crash log: drive.example.com/ios17-crash.log',
  },
  {
    title: 'Two-decimal rounding error on invoice totals over $10,000',
    desc: 'Invoices with subtotals over $10,000 display incorrect totals due to floating-point rounding. For example, $10,250.005 rounds to $10,250.00 instead of $10,250.01. Affects tax calculations and final totals. Finance team has flagged discrepancies.',
    steps: '1. Create an invoice with line items totaling exactly $10,250.005\n2. Apply 0% tax\n3. View the invoice preview\n4. Note the displayed total\n5. Compare to expected total',
    exp: 'Total displayed as $10,250.01 (standard banker\'s rounding).',
    act: 'Total displayed as $10,250.00. Download PDF shows same incorrect value.',
    env: 'All browsers, App v5.1.0, Production',
    sev: 'High', pri: 'P2', comp: 'Billing / Invoice Engine', rep: 'Finance Team',
    exc: "JavaScript floating point: (10250.005).toFixed(2) === '10250.00'",
    att: 'Invoice sample with discrepancy: drive.example.com/invoice-rounding.pdf',
  },
  {
    title: 'Autocomplete dropdown blocks form submit button on mobile',
    desc: 'On mobile devices, when the address autocomplete dropdown is open and a suggestion is tapped, the dropdown closes but its invisible overlay remains over the Submit button, making it impossible to submit the form. Users must scroll down past the button area to dismiss.',
    steps: '1. Open app on any iOS/Android device\n2. Navigate to shipping address form\n3. Tap the street address field\n4. Type 3+ characters and wait for autocomplete\n5. Tap any autocomplete suggestion\n6. Try to tap Submit button',
    exp: 'Dropdown closes, field populates, Submit button is tappable.',
    act: 'Dropdown closes visually but an invisible z-index overlay remains. Submit button does not respond to taps.',
    env: 'iOS 16/17, Android 13, all mobile browsers, App v4.5.0',
    sev: 'High', pri: 'P2', comp: 'Forms / Autocomplete', rep: 'Mobile QA',
    exc: '',
    att: 'Video on device: drive.example.com/mobile-overlay-bug.mp4',
  },
  {
    title: 'Database connection pool exhausted under moderate load',
    desc: 'Under moderate load (> 200 concurrent users), the application starts returning "503 Service Unavailable" due to database connection pool exhaustion. Pool size is set to 10 — far too low. Average query time increases from 40ms to 8000ms before connections time out.',
    steps: '1. Run load test with 250 concurrent simulated users\n2. Each user performs: login > dashboard view > 3 API calls\n3. Monitor /api/healthz endpoint\n4. Monitor DB connection count',
    exp: 'Application handles 250 concurrent users with < 200ms p95 response time.',
    act: '503 errors start at ~220 concurrent users. DB shows 10/10 connections used. Avg response time spikes to 8s.',
    env: 'Production, AWS RDS PostgreSQL, App v3.9.0',
    sev: 'Critical', pri: 'P1', comp: 'Database / Connection Pool', rep: 'DevOps Team',
    exc: 'Error: Connection pool exhausted\n  at Pool.connect (pg-pool/index.js:74)\n  at async UserController.getDashboard\nHTTP 503 Service Unavailable',
    att: 'Load test report: drive.example.com/load-test-results.html',
  },
  {
    title: 'CSV import fails for files with UTF-8 BOM encoding',
    desc: 'Importing customer data via CSV fails with a parsing error when the file has UTF-8 BOM (Byte Order Mark) encoding, which is the default export format from Microsoft Excel on Windows. Files saved as plain UTF-8 import correctly.',
    steps: '1. Export a CSV from Microsoft Excel on Windows (saves as UTF-8 BOM by default)\n2. Navigate to Data Import > Customers\n3. Upload the BOM-encoded CSV\n4. Click Import\n5. Observe error',
    exp: 'CSV imports correctly; BOM is stripped transparently.',
    act: 'Error: "Invalid header row detected. Expected \'email\', got \'\\uFEFFemail\'."',
    env: 'All browsers, App v4.3.0, Production and Staging',
    sev: 'Medium', pri: 'P3', comp: 'Data Import / CSV Parser', rep: 'Support Team',
    exc: "ParseError: Invalid header — received '\\uFEFFemail' at column 0\n  at CSVParser.parseHeader (csv-importer.js:44)",
    att: 'Sample BOM CSV: drive.example.com/sample-bom.csv',
  },
  {
    title: 'WebSocket disconnects every 30s in corporate proxy environments',
    desc: 'Real-time collaboration features (shared editing, live cursors, presence indicators) break every 30 seconds for users behind corporate HTTP proxies. The WebSocket connection drops and reconnects, causing data loss of the last edit. Regular ISP connections are unaffected.',
    steps: '1. Connect to corporate VPN or HTTP proxy\n2. Open a shared document\n3. Start typing\n4. Wait 30 seconds without activity\n5. Resume typing\n6. Observe connection status indicator',
    exp: 'WebSocket stays connected (heartbeat pings should keep it alive).',
    act: 'Connection drops at 30s mark (proxy timeout). Reconnection takes 3-5s. Last edit before drop is lost.',
    env: 'Corporate proxy networks, Chrome/Firefox, App v4.8.0',
    sev: 'High', pri: 'P2', comp: 'Real-time / WebSocket', rep: 'Enterprise Support',
    exc: 'WebSocket connection closed: code 1006 (Abnormal Closure)\nReconnecting... [attempt 1/5]\nCORS error on WebSocket upgrade in proxy environment',
    att: 'Network trace: drive.example.com/ws-proxy-trace.pcap',
  },
  {
    title: 'Password reset link expires immediately when timezone is non-UTC',
    desc: 'Users in timezones behind UTC (Americas) receive password reset emails where the 1-hour expiry link has already expired upon arrival. Root cause appears to be token expiry calculated in UTC but compared against local server time.',
    steps: '1. Set system timezone to America/New_York (UTC-5)\n2. Click "Forgot Password" for any account\n3. Check email — link arrives within 2 minutes\n4. Click the reset link immediately',
    exp: 'Reset link works; user can set new password.',
    act: '"This reset link has expired. Please request a new one." Link is expired on first click.',
    env: 'Any timezone behind UTC, App v3.7.0, Production',
    sev: 'High', pri: 'P2', comp: 'Auth / Password Reset', rep: 'Support Team',
    exc: "TokenExpiredError: jwt expired\n  iat: 1701900000, exp: 1701903600, current: 1701921600\n  at verify (jsonwebtoken/verify.js:89)",
    att: '',
  },
  {
    title: 'Role-based access control allows viewers to delete records',
    desc: 'Users with "Viewer" role (read-only) are able to delete records via direct API calls even though the UI correctly hides the Delete button. The backend endpoint /api/records/{id} DELETE does not validate the user\'s role before processing the deletion.',
    steps: '1. Log in as a user with Viewer role\n2. Open browser DevTools\n3. Note a record ID from the GET /api/records response\n4. Send DELETE /api/records/{id} with valid auth token\n5. Refresh the UI',
    exp: 'API returns 403 Forbidden for Viewer role on DELETE endpoints.',
    act: 'Record is deleted. API returns 204 No Content.',
    env: 'All environments, API v2, Production',
    sev: 'Critical', pri: 'P1', comp: 'Auth / RBAC / API', rep: 'Security Team',
    exc: 'HTTP 204 No Content (expected 403 Forbidden)\nDELETE /api/records/7842 - 204 - viewer_user@corp.com',
    att: 'Curl reproduction: drive.example.com/rbac-exploit.sh',
  },
  {
    title: 'Infinite scroll triggers duplicate API calls on slow connections',
    desc: 'On connections with > 500ms latency, scrolling to the bottom of a list fires the "load more" API call 3-4 times in rapid succession (IntersectionObserver fires repeatedly before the response arrives). Results in duplicate items appearing in the list.',
    steps: '1. Open Chrome DevTools > Network > throttle to "Slow 3G"\n2. Navigate to any paginated list (e.g. /customers)\n3. Scroll to the bottom\n4. Watch the Network tab\n5. Observe the list items',
    exp: 'One API call per scroll-to-bottom; no duplicate items.',
    act: '3-4 identical GET /api/customers?page=2 calls fire. List shows duplicate customer rows.',
    env: 'Slow/high-latency connections, Chrome/Firefox, App v4.6.0',
    sev: 'Medium', pri: 'P3', comp: 'Frontend / Infinite Scroll', rep: 'Frontend Team',
    exc: "GET /api/customers?page=2 called 4 times in 800ms\nDuplicate key warning: 'customer_4821' already in list",
    att: 'Network waterfall: drive.example.com/duplicate-calls.png',
  },
  {
    title: 'Dark mode toggle resets to light on every page navigation',
    desc: 'Users who enable dark mode find that it resets to light mode every time they navigate to a different page or refresh. The preference is not being persisted to localStorage or user profile settings.',
    steps: '1. Log in\n2. Click the theme toggle to enable dark mode\n3. Verify dark mode is active\n4. Navigate to any other page (e.g. Settings)\n5. Observe theme',
    exp: 'Dark mode preference persists across navigation and sessions.',
    act: 'Theme reverts to light mode on every page navigation.',
    env: 'All browsers, App v5.0.0, Production',
    sev: 'Low', pri: 'P4', comp: 'UI / Theme / Persistence', rep: 'UX Team',
    exc: '',
    att: '',
  },
  {
    title: 'API endpoint returns full PII data in error response body',
    desc: 'The /api/users/search endpoint, when given a malformed query parameter, returns a 400 error response that includes the full user object (including hashed passwords, SSNs, and phone numbers) in the error "debug" field. This is a significant data exposure vulnerability.',
    steps: '1. Send GET /api/users/search?q=<script>alert(1)</script> with a valid admin auth token\n2. Observe the 400 error response body\n3. Examine the "debug" field',
    exp: 'API returns 400 with generic error message. No user data exposed.',
    act: 'Response contains full user objects including password_hash, ssn, and phone in debug field.',
    env: 'Production and Staging, API v2',
    sev: 'Critical', pri: 'P1', comp: 'API / Security / User Search', rep: 'Security Audit',
    exc: 'HTTP 400 Bad Request\n{"error":"Invalid query","debug":{"users":[{"id":1,"email":"...","password_hash":"$2b$10$...","ssn":"XXX-XX-XXXX"}]}}',
    att: 'Full response: drive.example.com/pii-exposure-redacted.json',
  },
];

export function getRandomSample(): SampleField {
  return SAMPLES[Math.floor(Math.random() * SAMPLES.length)];
}
