import { useEffect } from 'react';
import { ResultsPanel } from './ResultsPanel';
import { gradeMeta, scoreColor } from '../lib/analysis';
import { useToastTrigger } from '../components/Toast';
import type { HistoryItem, User } from '../lib/types';

interface Props {
  item: HistoryItem;
  user: User;
  onClose: () => void;
}

export function ResultsModal({ item, user, onClose }: Props) {
  const toast = useToastTrigger();

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [onClose]);

  const downloadFile = (content: string, filename: string, type: string) => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([content], { type }));
    a.download = filename; a.click();
  };
  const safeFilename = (s: string) => s.replace(/\s+/g, '_').slice(0, 40);

  return (
    <div className="bl-modal-overlay" onClick={e => { if (e.target === e.currentTarget) onClose(); }} data-testid="modal-overlay">
      <div className="bl-modal-box">
        <button
          onClick={onClose}
          data-testid="button-modal-close"
          style={{ float: 'right', fontSize: '1.3rem', cursor: 'pointer', color: '#a09a92', background: 'none', border: 'none', lineHeight: 1 }}
          onMouseEnter={e => e.currentTarget.style.color = '#1a1714'}
          onMouseLeave={e => e.currentTarget.style.color = '#a09a92'}
        >✕</button>
        <h2 className="bl-serif" style={{ fontSize: '1.35rem', marginBottom: '.28rem', paddingRight: '2rem' }}>{item.title}</h2>
        <div className="bl-mono" style={{ fontSize: '.76rem', color: '#a09a92', marginBottom: '1.1rem', paddingBottom: '.9rem', borderBottom: '1px solid #d4cfc5' }}>
          {new Date(item.timestamp).toLocaleString()} · {user.name} ({user.role})
        </div>
        <ResultsPanel
          result={item.parsed}
          title={item.title}
          excRaw={item.fields?.exc || ''}
          onDownloadTXT={() => {
            downloadFile(item.parsed?.rewritten_report || '', `${safeFilename(item.title)}_report.txt`, 'text/plain');
            toast('⬇ Downloaded TXT');
          }}
          onDownloadMD={() => {
            const gm = gradeMeta(item.score);
            const md = `# Bug Report: ${item.title}\n\n**Score:** ${item.score}/100  **Grade:** ${gm.label}\n\n---\n\n${item.parsed?.rewritten_report || ''}`;
            downloadFile(md, `${safeFilename(item.title)}_report.md`, 'text/markdown');
            toast('⬇ Downloaded MD');
          }}
          onDownloadHTML={() => {
            const gm = gradeMeta(item.score);
            const c = scoreColor(item.score);
            const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Bug Report</title><style>body{font-family:Georgia,serif;max-width:740px;margin:2rem auto;padding:1.5rem;color:#1a1714;background:#f5f2ee}h1{font-size:1.5rem}.meta{font-family:monospace;font-size:.78rem;color:#7a756e;margin-bottom:1.4rem;padding-bottom:.9rem;border-bottom:1px solid #d4cfc5}.chip{display:inline-block;padding:.28rem .85rem;border-radius:20px;font-family:monospace;font-weight:700;color:${c};background:#f5f2ee;border:2px solid ${c};margin-right:.45rem}.grade{display:inline-block;padding:.22rem .75rem;border-radius:12px;font-family:monospace;font-size:.78rem;font-weight:600;background:${gm.bg};color:${gm.color}}pre{background:#f0ede7;border:1px solid #d4cfc5;border-radius:8px;padding:1.1rem;font-family:monospace;font-size:.8rem;line-height:1.8;white-space:pre-wrap;margin-top:1.1rem}.foot{margin-top:1.8rem;padding-top:.9rem;border-top:1px solid #d4cfc5;font-size:.72rem;color:#a09a92;font-family:monospace}</style></head><body><h1>Bug Report</h1><div class="meta">Generated by BugLens · ${new Date(item.timestamp).toLocaleString()} · ${user.name}</div><span class="chip">${item.score}/100</span><span class="grade">${gm.label}</span><pre>${(item.parsed?.rewritten_report || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre><div class="foot">BugLens Defect Quality Checker</div></body></html>`;
            downloadFile(html, `${safeFilename(item.title)}_report.html`, 'text/html');
            toast('⬇ Downloaded HTML');
          }}
          onDownloadJSON={() => {
            const gm = gradeMeta(item.score);
            const out = { meta: { generated: new Date().toISOString(), analyst: user.name, tool: 'BugLens' }, title: item.title, score: item.score, grade: gm.label, ...item.parsed };
            downloadFile(JSON.stringify(out, null, 2), `${safeFilename(item.title)}_analysis.json`, 'application/json');
            toast('⬇ Downloaded JSON');
          }}
        />
      </div>
    </div>
  );
}
